(ns redantd.antd)

(def components
  '[Button
    Button.Group
    Icon
    Typography
    Typography.Text
    Typography.Title
    Typography.Paragraph
    Row
    Col
    Layout
    Layout.Header
    Layout.Content
    Layout.Footer
    Layout.Sider
    Affix
    Breadcrumb
    Breadcrumb.Item
    Breadcrumb.Separator
    Dropdown
    Dropdown.Button
    Menu
    Menu.Item
    Menu.SubMenu
    Menu.ItemGroup
    Menu.Divider
    Pagination
    PageHeader
    Steps
    Steps.Step
    AutoComplete
    AutoComplete.Option
    Checkbox
    Checkbox.Group
    Cascader
    DatePicker
    MonthPicker
    RangePicker
    WeekPicker
    Form
    Form.Item
    InputNumber
    Input
    Input.TextArea
    Input.Search
    Input.Group
    Input.Password
    Mentions
    Mentions.Option
    Rate
    Radio
    Radio.Group
    Radio.Button
    Switch
    Slider
    Select
    Select.OptGroup
    Select.Option
    TreeSelect
    TreeSelect.TreeNode
    Transfer
    TimePicker
    Upload
    Avatar
    Badge
    Comment
    Collapse
    Collapse.Panel
    Carousel
    Card
    Card.Grid
    Card.Meta
    Calendar
    Descriptions
    Description.Item
    Empty
    List
    List.Item
    List.Item.Meta
    Popover
    Statistic
    Statistic.Countdown
    Tree
    Tree.TreeNode
    Tree.DirectoryTree
    Tooltip
    Timeline
    Timeline.Item
    Tag
    Tag.CheckableTag
    Tabs
    Tabs.TabPane
    Table
    Table.ColumnGroup
    Table.Column
    Alert
    Drawer
    Modal
    Progress
    Popconfirm
    Result
    Spin
    Skeleton
    Anchor
    Anchor.Link
    BackTop
    ConfigProvider
    Divider
    LocaleProvider])

(def funcs '[message.config
             message.destroy
             message.error
             message.info
             message.loading
             message.success
             message.warn
             message.warning
             Modal.confirm
             Modal.error
             Modal.info
             Modal.success
             Modal.warning
             notification.close
             notification.config
             notification.destroy
             notification.error
             notification.info
             notification.open
             notification.success
             notification.warn
             notification.warning])

(def form-funcs '[getFieldError
                  getFieldsError
                  getFieldsValue
                  getFieldValue
                  isFieldsTouched
                  isFieldTouched
                  isFieldValidating
                  resetFields
                  setFields
                  setFieldsValue])
